### ISSUE TITLE
Raspberry Pi problem

### ISSUE THREAD

**Issue by SA7BNT** [theyosh/DreamboxReStream#3]
Hey,

is it possible to run DreamboxReStream on a Raspberry Pi 3b (Latest Raspbian)??
I maked a test but getting an error.
`pi@raspberrypi:~ $ cvlc --version
VLC media player 3.0.6 Vetinari (revision 3.0.6-0-g5803e85f73)
VLC version 3.0.6 Vetinari (3.0.6-0-g5803e85f73)
Compiled by serge on arm-build.pitowers.org (Mar  5 2019 15:20:31)
Compiler: gcc version 6.3.0 20170516 (Raspbian 6.3.0-18+rpi1+deb9u1)
This program comes with NO WARRANTY, to the extent permitted by law.
You may redistribute it under the terms of the GNU General Public Licence;
see the file named COPYING for details.
Written by the VideoLAN team; see the AUTHORS file.
pi@raspberrypi:~ $ `
![Bildschirmfoto 2019-04-23 um 19 38 05](https://user-images.githubusercontent.com/35367117/56603286-bc327500-65ff-11e9-9ed0-6d5bced5ab67.png)
I also installed h264 library.
[http://jollejolles.com/installing-ffmpeg-with-h264-support-on-raspberry-pi/](url)
The log (/tmp/restream.vlc.log.txt) shows nothing.
Have you ever tried to run it on a Pi??

**Comment by theyosh** [comment]
Hi, sorry for not replying earlier. In the current state with the code it will not work in a Pi due to slow CPU power. Using VLC, does require a pretty strong CPU. And the Pi has not.

There is a solution to use ffmpeg with hardware encoding for the Pi. But that means manual compiling ffmpeg on a pi, and rewrite of the hole streaming part... Which with this rather old code is a bit of work...

So, I will keep this in mind, and maybe someday it will work. But as I do not use it much, this project is not that active...
